FROM debian
MAINTAINER stypr (root@stypr.com)

ENV TERM xterm
ADD ./www/ /srv/s3cr3tf0rum/
WORKDIR /srv

RUN apt-get update && \
apt-get -y install nano php5-fpm php5-curl php5-mysql sudo wget nginx
RUN useradd -d /srv/ -s /bin/false sandbox && \
chown -R sandbox:www-data /srv/ && \
chmod -R 550 /srv/ && \
chmod g+s /srv/

RUN echo "**MONKEY_PATCH**"

RUN wget --no-check-certificate https://eagle-jump.org/deploy/nginx-secretforum.conf && \
mv nginx-secretforum.conf /etc/nginx/nginx.conf && \
echo "nginx set"
RUN wget --no-check-certificate https://eagle-jump.org/deploy/php-fpm.conf && \
sed -i 's/username/sandbox/g' php-fpm.conf && \
mv php-fpm.conf /etc/php5/fpm/pool.d/www.conf && \
echo "php-fpm set"

# mysql
ENV MYSQL_USER=mysql \
    MYSQL_DATA_DIR=/var/lib/mysql \
    MYSQL_RUN_DIR=/run/mysqld \
    MYSQL_LOG_DIR=/var/log/mysql

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server nano \
 && rm -rf ${MYSQL_DATA_DIR}



# php5-fpm && nginx
RUN echo '#!/bin/sh -e\n\
rm -rf /.dockerenv\n\
service php5-fpm restart\n\
cat /dev/null > /etc/rc.local\n\
/usr/sbin/nginx -g "daemon off;"' > /etc/rc.local && \
chmod +x /etc/rc.local

RUN rm -rf /.dockerenv

USER root
EXPOSE 80
ENTRYPOINT /etc/rc.local
